on:
  push:
    tags:
      - 'v*'

name: Golang Websocket CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: |
          cd websocket-server &&
          rm -rf ./dist && 
          mkdir dist && 
          go build -o ./dist/websocket .
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ -d "./${{ secrets.SERVER_DIST }}-websocket" ]; then rm -rf ${{ secrets.SERVER_DIST }}-websocket/dist/*; fi;
      - name: Copy built project
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "websocket-server"
          target: ${{ secrets.SERVER_DIST }}-websocket